[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

