[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
from = "/assets/*"
to = "/assets"
status = 200

[[redirects]]
from = "/data.json"
to = "/data.json:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

