[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
from = "/assets/*"
to = "/assets:splat"
status = 200

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/sever/app/:splat"

