[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
from = "/*"
force = true
to = "/index.html"
status = 200

[[redirects]]
force = true
from = "/api/*"
to = "/server/app/:splat"
status = 200

